net stop JAQCMetodology_PHP8
net stop JAQCMetodology_PHP73
net stop JAQCMetodology_PHP74
net stop JAQCMetodology_MariaDB
net stop JAQCMetodology_MariaDBx64

sc delete JAQCMetodology_PHP8
sc delete JAQCMetodology_PHP73
sc delete JAQCMetodology_PHP74
sc delete JAQCMetodology_MariaDB
sc delete JAQCMetodology_MariaDBx64
pause
